- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansible-test
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible-test
      name: ansibleNet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible-test
      name: ansibleSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ansibleNet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansible-test
      #allocation_method: Static
      name: ansiblePublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible-test
      name: ansibleNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1001
          direction: Outbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 8043
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ansible-test
      name: ansibleNIC
      virtual_network: ansibleNet
      subnet: ansibleSubnet
      public_ip_name: ansiblePublicIP
      security_group: ansibleNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansible-test
      name: ansibleTalendVM
      vm_size: Standard_B2s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDB/qPJTyBhIGN4Zb+mjOQduDoRMnIeksFuVkVhono6jHNLoTVKTC5rZhh6nStOGqdFqzXeTLjbhv0YRofD/ZahfmyyFmPHt8TOCWvSgOSw3Yo+vsczJEB9jsUtmPAJeTi4EK5pROCTGszvHbp5PNTKa6QJ5N8QYlJOhLA+LkVkKyXfqJux/3BPailnBIyzySbe0GTJL0+xxf1ffYSJcBgtNVaCtxjuEycTXrC9j2zDMjl878gjjdNQBF8z9IPYKnsxNpefcRmmmPmDEY4JYyR8XmlCAq62BRkq7fyWUXH5pLljgAM9TgxdXpV3aNvbrl6hVtnJ40Rzbx8v4IrkctGCXR8QCQWv+G7mNQlYVRV7PCbAO+NgtBS8aleWeqitPVy2YXYBhfFGuzoxxgKUi3VMza5M2OtQM4GdMSjkIIOBqHIRw95q8Sa18xytnVMyXQbtSBnSBIa1wbA2Y2dzqzjRcqbr0yU5BxGZKWzc8Y2hLFqAj2JU24Vyi2lvh8YlRB/9JDjb5WXGvy71xL5JagoscRWlBIiNMxBlUzjt0v4b57oTHX2QTWmSCGNBzV7tsmfmZNcCEDS39PM7peiwDZ00UD98agvQzOfuLjiUh5RLoh0Ol2pi1gnG//v3YXVnoumdA9+N1Org3winLl6GaGDHI0My4t49tAQVmbPtiwK0lw== cloud_user@eaca0b8ca1b342ffb530b9a7d1aa6ce63c.mylabserver.com"
      network_interfaces: ansibleNIC
      image:
        offer: 0001-com-ubuntu-server-focal
        publisher: Canonical
        sku: 20_04-lts
        version: latest
