- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansible-test
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible-test
      name: ansibleNet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible-test
      name: ansibleSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ansibleNet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansible-test
      #allocation_method: Static
      name: ansiblePublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible-test
      name: ansibleNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: HTTP
          protocol: Tcp
          destination_port_range: 80
          access: Allow
          priority: 1001
          direction: Outbound
        - name: Talend_port
          protocol: Tcp
          destination_port_range: 8043
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ansible-test
      name: ansibleNIC
      virtual_network: ansibleNet
      subnet: ansibleSubnet
      public_ip_name: ansiblePublicIP
      security_group: ansibleNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansible-test
      name: ansibleTalendVM
      vm_size: Standard_B2s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbXLuvwiQU2s6YnEFlM/maE/pzELV2tS8gjdNrbD45dfMd2Iv4P7mSuhvC8Gb+uBe0i/PkqFbaN8lti7hEgcGnM6jxdyOnqbA3NVxE1IEWPuD9eStBgUCJA7BFiWugDcpnNFzBoq9hpcv7UhMXaKTeG2i4kFzkA0KhKf5+BvYVdaYc48scGrTqVa8dPMMASkI4rYS0uO7pqsDBGFleow6f1ATlanuBxyYiIo+tqEQ9i0H5XnP9lFonCGdIJIgZcwfKOUbZ4k0ix8HN9SZTynZ03skRI7nZXVqu0sI0G3ORWTlTPLjN3EUCVJTnrSVu8UjLnVPRA++9CJcciweBNfMH DockerJenkins@vmNewMarketJenkins"
      network_interfaces: ansibleNIC
      image:
        offer: 0001-com-ubuntu-server-focal
        publisher: Canonical
        sku: 20_04-lts
        version: latest
